// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: com/mars/masterserver/net/decoder/MsgProtocol.proto

package com.mars.masterserver.net.decoder;

public final class MsgProtocol {
  private MsgProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MsgRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mars.masterserver.net.decoder.MsgRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
     */
    boolean hasContent();
    /**
     * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
     */
    com.mars.masterserver.net.decoder.MsgProtocol.Content getContent();
    /**
     * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
     */
    com.mars.masterserver.net.decoder.MsgProtocol.ContentOrBuilder getContentOrBuilder();
  }
  /**
   * Protobuf type {@code com.mars.masterserver.net.decoder.MsgRequest}
   */
  public static final class MsgRequest extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.mars.masterserver.net.decoder.MsgRequest)
      MsgRequestOrBuilder {
    // Use MsgRequest.newBuilder() to construct.
    private MsgRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MsgRequest(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MsgRequest defaultInstance;
    public static MsgRequest getDefaultInstance() {
      return defaultInstance;
    }

    public MsgRequest getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MsgRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.mars.masterserver.net.decoder.MsgProtocol.Content.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = content_.toBuilder();
              }
              content_ = input.readMessage(com.mars.masterserver.net.decoder.MsgProtocol.Content.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(content_);
                content_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mars.masterserver.net.decoder.MsgProtocol.internal_static_com_mars_masterserver_net_decoder_MsgRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mars.masterserver.net.decoder.MsgProtocol.internal_static_com_mars_masterserver_net_decoder_MsgRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest.class, com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest.Builder.class);
    }

    public static com.google.protobuf.Parser<MsgRequest> PARSER =
        new com.google.protobuf.AbstractParser<MsgRequest>() {
      public MsgRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgRequest(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MsgRequest> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.mars.masterserver.net.decoder.MsgProtocol.Content content_;
    /**
     * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
     */
    public com.mars.masterserver.net.decoder.MsgProtocol.Content getContent() {
      return content_;
    }
    /**
     * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
     */
    public com.mars.masterserver.net.decoder.MsgProtocol.ContentOrBuilder getContentOrBuilder() {
      return content_;
    }

    private void initFields() {
      id_ = "";
      content_ = com.mars.masterserver.net.decoder.MsgProtocol.Content.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, content_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, content_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mars.masterserver.net.decoder.MsgRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mars.masterserver.net.decoder.MsgRequest)
        com.mars.masterserver.net.decoder.MsgProtocol.MsgRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mars.masterserver.net.decoder.MsgProtocol.internal_static_com_mars_masterserver_net_decoder_MsgRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mars.masterserver.net.decoder.MsgProtocol.internal_static_com_mars_masterserver_net_decoder_MsgRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest.class, com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest.Builder.class);
      }

      // Construct using com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getContentFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (contentBuilder_ == null) {
          content_ = com.mars.masterserver.net.decoder.MsgProtocol.Content.getDefaultInstance();
        } else {
          contentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mars.masterserver.net.decoder.MsgProtocol.internal_static_com_mars_masterserver_net_decoder_MsgRequest_descriptor;
      }

      public com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest getDefaultInstanceForType() {
        return com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest.getDefaultInstance();
      }

      public com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest build() {
        com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest buildPartial() {
        com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest result = new com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (contentBuilder_ == null) {
          result.content_ = content_;
        } else {
          result.content_ = contentBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest) {
          return mergeFrom((com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest other) {
        if (other == com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasContent()) {
          mergeContent(other.getContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mars.masterserver.net.decoder.MsgProtocol.MsgRequest) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private com.mars.masterserver.net.decoder.MsgProtocol.Content content_ = com.mars.masterserver.net.decoder.MsgProtocol.Content.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.mars.masterserver.net.decoder.MsgProtocol.Content, com.mars.masterserver.net.decoder.MsgProtocol.Content.Builder, com.mars.masterserver.net.decoder.MsgProtocol.ContentOrBuilder> contentBuilder_;
      /**
       * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
       */
      public com.mars.masterserver.net.decoder.MsgProtocol.Content getContent() {
        if (contentBuilder_ == null) {
          return content_;
        } else {
          return contentBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
       */
      public Builder setContent(com.mars.masterserver.net.decoder.MsgProtocol.Content value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          contentBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
       */
      public Builder setContent(
          com.mars.masterserver.net.decoder.MsgProtocol.Content.Builder builderForValue) {
        if (contentBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          contentBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
       */
      public Builder mergeContent(com.mars.masterserver.net.decoder.MsgProtocol.Content value) {
        if (contentBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              content_ != com.mars.masterserver.net.decoder.MsgProtocol.Content.getDefaultInstance()) {
            content_ =
              com.mars.masterserver.net.decoder.MsgProtocol.Content.newBuilder(content_).mergeFrom(value).buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          contentBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
       */
      public Builder clearContent() {
        if (contentBuilder_ == null) {
          content_ = com.mars.masterserver.net.decoder.MsgProtocol.Content.getDefaultInstance();
          onChanged();
        } else {
          contentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
       */
      public com.mars.masterserver.net.decoder.MsgProtocol.Content.Builder getContentBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getContentFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
       */
      public com.mars.masterserver.net.decoder.MsgProtocol.ContentOrBuilder getContentOrBuilder() {
        if (contentBuilder_ != null) {
          return contentBuilder_.getMessageOrBuilder();
        } else {
          return content_;
        }
      }
      /**
       * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.mars.masterserver.net.decoder.MsgProtocol.Content, com.mars.masterserver.net.decoder.MsgProtocol.Content.Builder, com.mars.masterserver.net.decoder.MsgProtocol.ContentOrBuilder> 
          getContentFieldBuilder() {
        if (contentBuilder_ == null) {
          contentBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.mars.masterserver.net.decoder.MsgProtocol.Content, com.mars.masterserver.net.decoder.MsgProtocol.Content.Builder, com.mars.masterserver.net.decoder.MsgProtocol.ContentOrBuilder>(
                  getContent(),
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        return contentBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.mars.masterserver.net.decoder.MsgRequest)
    }

    static {
      defaultInstance = new MsgRequest(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mars.masterserver.net.decoder.MsgRequest)
  }

  public interface MsgResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mars.masterserver.net.decoder.MsgResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>optional string id = 1;</code>
     */
    java.lang.String getId();
    /**
     * <code>optional string id = 1;</code>
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
     */
    boolean hasContent();
    /**
     * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
     */
    com.mars.masterserver.net.decoder.MsgProtocol.Content getContent();
    /**
     * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
     */
    com.mars.masterserver.net.decoder.MsgProtocol.ContentOrBuilder getContentOrBuilder();
  }
  /**
   * Protobuf type {@code com.mars.masterserver.net.decoder.MsgResponse}
   */
  public static final class MsgResponse extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.mars.masterserver.net.decoder.MsgResponse)
      MsgResponseOrBuilder {
    // Use MsgResponse.newBuilder() to construct.
    private MsgResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private MsgResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final MsgResponse defaultInstance;
    public static MsgResponse getDefaultInstance() {
      return defaultInstance;
    }

    public MsgResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private MsgResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              id_ = bs;
              break;
            }
            case 18: {
              com.mars.masterserver.net.decoder.MsgProtocol.Content.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = content_.toBuilder();
              }
              content_ = input.readMessage(com.mars.masterserver.net.decoder.MsgProtocol.Content.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(content_);
                content_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mars.masterserver.net.decoder.MsgProtocol.internal_static_com_mars_masterserver_net_decoder_MsgResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mars.masterserver.net.decoder.MsgProtocol.internal_static_com_mars_masterserver_net_decoder_MsgResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse.class, com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<MsgResponse> PARSER =
        new com.google.protobuf.AbstractParser<MsgResponse>() {
      public MsgResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MsgResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<MsgResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private java.lang.Object id_;
    /**
     * <code>optional string id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          id_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CONTENT_FIELD_NUMBER = 2;
    private com.mars.masterserver.net.decoder.MsgProtocol.Content content_;
    /**
     * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
     */
    public boolean hasContent() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
     */
    public com.mars.masterserver.net.decoder.MsgProtocol.Content getContent() {
      return content_;
    }
    /**
     * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
     */
    public com.mars.masterserver.net.decoder.MsgProtocol.ContentOrBuilder getContentOrBuilder() {
      return content_;
    }

    private void initFields() {
      id_ = "";
      content_ = com.mars.masterserver.net.decoder.MsgProtocol.Content.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, content_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, content_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mars.masterserver.net.decoder.MsgResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mars.masterserver.net.decoder.MsgResponse)
        com.mars.masterserver.net.decoder.MsgProtocol.MsgResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mars.masterserver.net.decoder.MsgProtocol.internal_static_com_mars_masterserver_net_decoder_MsgResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mars.masterserver.net.decoder.MsgProtocol.internal_static_com_mars_masterserver_net_decoder_MsgResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse.class, com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse.Builder.class);
      }

      // Construct using com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getContentFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        if (contentBuilder_ == null) {
          content_ = com.mars.masterserver.net.decoder.MsgProtocol.Content.getDefaultInstance();
        } else {
          contentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mars.masterserver.net.decoder.MsgProtocol.internal_static_com_mars_masterserver_net_decoder_MsgResponse_descriptor;
      }

      public com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse getDefaultInstanceForType() {
        return com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse.getDefaultInstance();
      }

      public com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse build() {
        com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse buildPartial() {
        com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse result = new com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (contentBuilder_ == null) {
          result.content_ = content_;
        } else {
          result.content_ = contentBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse) {
          return mergeFrom((com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse other) {
        if (other == com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse.getDefaultInstance()) return this;
        if (other.hasId()) {
          bitField0_ |= 0x00000001;
          id_ = other.id_;
          onChanged();
        }
        if (other.hasContent()) {
          mergeContent(other.getContent());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mars.masterserver.net.decoder.MsgProtocol.MsgResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object id_ = "";
      /**
       * <code>optional string id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            id_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string id = 1;</code>
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }

      private com.mars.masterserver.net.decoder.MsgProtocol.Content content_ = com.mars.masterserver.net.decoder.MsgProtocol.Content.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          com.mars.masterserver.net.decoder.MsgProtocol.Content, com.mars.masterserver.net.decoder.MsgProtocol.Content.Builder, com.mars.masterserver.net.decoder.MsgProtocol.ContentOrBuilder> contentBuilder_;
      /**
       * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
       */
      public boolean hasContent() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
       */
      public com.mars.masterserver.net.decoder.MsgProtocol.Content getContent() {
        if (contentBuilder_ == null) {
          return content_;
        } else {
          return contentBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
       */
      public Builder setContent(com.mars.masterserver.net.decoder.MsgProtocol.Content value) {
        if (contentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          content_ = value;
          onChanged();
        } else {
          contentBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
       */
      public Builder setContent(
          com.mars.masterserver.net.decoder.MsgProtocol.Content.Builder builderForValue) {
        if (contentBuilder_ == null) {
          content_ = builderForValue.build();
          onChanged();
        } else {
          contentBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
       */
      public Builder mergeContent(com.mars.masterserver.net.decoder.MsgProtocol.Content value) {
        if (contentBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              content_ != com.mars.masterserver.net.decoder.MsgProtocol.Content.getDefaultInstance()) {
            content_ =
              com.mars.masterserver.net.decoder.MsgProtocol.Content.newBuilder(content_).mergeFrom(value).buildPartial();
          } else {
            content_ = value;
          }
          onChanged();
        } else {
          contentBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
       */
      public Builder clearContent() {
        if (contentBuilder_ == null) {
          content_ = com.mars.masterserver.net.decoder.MsgProtocol.Content.getDefaultInstance();
          onChanged();
        } else {
          contentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
       */
      public com.mars.masterserver.net.decoder.MsgProtocol.Content.Builder getContentBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getContentFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
       */
      public com.mars.masterserver.net.decoder.MsgProtocol.ContentOrBuilder getContentOrBuilder() {
        if (contentBuilder_ != null) {
          return contentBuilder_.getMessageOrBuilder();
        } else {
          return content_;
        }
      }
      /**
       * <code>optional .com.mars.masterserver.net.decoder.Content content = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          com.mars.masterserver.net.decoder.MsgProtocol.Content, com.mars.masterserver.net.decoder.MsgProtocol.Content.Builder, com.mars.masterserver.net.decoder.MsgProtocol.ContentOrBuilder> 
          getContentFieldBuilder() {
        if (contentBuilder_ == null) {
          contentBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              com.mars.masterserver.net.decoder.MsgProtocol.Content, com.mars.masterserver.net.decoder.MsgProtocol.Content.Builder, com.mars.masterserver.net.decoder.MsgProtocol.ContentOrBuilder>(
                  getContent(),
                  getParentForChildren(),
                  isClean());
          content_ = null;
        }
        return contentBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:com.mars.masterserver.net.decoder.MsgResponse)
    }

    static {
      defaultInstance = new MsgResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mars.masterserver.net.decoder.MsgResponse)
  }

  public interface ContentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.mars.masterserver.net.decoder.Content)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string body = 1;</code>
     */
    boolean hasBody();
    /**
     * <code>optional string body = 1;</code>
     */
    java.lang.String getBody();
    /**
     * <code>optional string body = 1;</code>
     */
    com.google.protobuf.ByteString
        getBodyBytes();

    /**
     * <code>optional bytes temp_body = 2;</code>
     */
    boolean hasTempBody();
    /**
     * <code>optional bytes temp_body = 2;</code>
     */
    com.google.protobuf.ByteString getTempBody();
  }
  /**
   * Protobuf type {@code com.mars.masterserver.net.decoder.Content}
   */
  public static final class Content extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.mars.masterserver.net.decoder.Content)
      ContentOrBuilder {
    // Use Content.newBuilder() to construct.
    private Content(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Content(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Content defaultInstance;
    public static Content getDefaultInstance() {
      return defaultInstance;
    }

    public Content getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Content(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              body_ = bs;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              tempBody_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.mars.masterserver.net.decoder.MsgProtocol.internal_static_com_mars_masterserver_net_decoder_Content_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.mars.masterserver.net.decoder.MsgProtocol.internal_static_com_mars_masterserver_net_decoder_Content_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.mars.masterserver.net.decoder.MsgProtocol.Content.class, com.mars.masterserver.net.decoder.MsgProtocol.Content.Builder.class);
    }

    public static com.google.protobuf.Parser<Content> PARSER =
        new com.google.protobuf.AbstractParser<Content>() {
      public Content parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Content(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Content> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int BODY_FIELD_NUMBER = 1;
    private java.lang.Object body_;
    /**
     * <code>optional string body = 1;</code>
     */
    public boolean hasBody() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string body = 1;</code>
     */
    public java.lang.String getBody() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          body_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string body = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBodyBytes() {
      java.lang.Object ref = body_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TEMP_BODY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString tempBody_;
    /**
     * <code>optional bytes temp_body = 2;</code>
     */
    public boolean hasTempBody() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional bytes temp_body = 2;</code>
     */
    public com.google.protobuf.ByteString getTempBody() {
      return tempBody_;
    }

    private void initFields() {
      body_ = "";
      tempBody_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getBodyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, tempBody_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBodyBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, tempBody_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.mars.masterserver.net.decoder.MsgProtocol.Content parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.Content parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.Content parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.Content parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.Content parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.Content parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.Content parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.Content parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.Content parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.mars.masterserver.net.decoder.MsgProtocol.Content parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.mars.masterserver.net.decoder.MsgProtocol.Content prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.mars.masterserver.net.decoder.Content}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.mars.masterserver.net.decoder.Content)
        com.mars.masterserver.net.decoder.MsgProtocol.ContentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.mars.masterserver.net.decoder.MsgProtocol.internal_static_com_mars_masterserver_net_decoder_Content_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.mars.masterserver.net.decoder.MsgProtocol.internal_static_com_mars_masterserver_net_decoder_Content_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.mars.masterserver.net.decoder.MsgProtocol.Content.class, com.mars.masterserver.net.decoder.MsgProtocol.Content.Builder.class);
      }

      // Construct using com.mars.masterserver.net.decoder.MsgProtocol.Content.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        body_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        tempBody_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.mars.masterserver.net.decoder.MsgProtocol.internal_static_com_mars_masterserver_net_decoder_Content_descriptor;
      }

      public com.mars.masterserver.net.decoder.MsgProtocol.Content getDefaultInstanceForType() {
        return com.mars.masterserver.net.decoder.MsgProtocol.Content.getDefaultInstance();
      }

      public com.mars.masterserver.net.decoder.MsgProtocol.Content build() {
        com.mars.masterserver.net.decoder.MsgProtocol.Content result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.mars.masterserver.net.decoder.MsgProtocol.Content buildPartial() {
        com.mars.masterserver.net.decoder.MsgProtocol.Content result = new com.mars.masterserver.net.decoder.MsgProtocol.Content(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.body_ = body_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.tempBody_ = tempBody_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.mars.masterserver.net.decoder.MsgProtocol.Content) {
          return mergeFrom((com.mars.masterserver.net.decoder.MsgProtocol.Content)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.mars.masterserver.net.decoder.MsgProtocol.Content other) {
        if (other == com.mars.masterserver.net.decoder.MsgProtocol.Content.getDefaultInstance()) return this;
        if (other.hasBody()) {
          bitField0_ |= 0x00000001;
          body_ = other.body_;
          onChanged();
        }
        if (other.hasTempBody()) {
          setTempBody(other.getTempBody());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.mars.masterserver.net.decoder.MsgProtocol.Content parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.mars.masterserver.net.decoder.MsgProtocol.Content) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object body_ = "";
      /**
       * <code>optional string body = 1;</code>
       */
      public boolean hasBody() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string body = 1;</code>
       */
      public java.lang.String getBody() {
        java.lang.Object ref = body_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            body_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string body = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBodyBytes() {
        java.lang.Object ref = body_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string body = 1;</code>
       */
      public Builder setBody(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        body_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string body = 1;</code>
       */
      public Builder clearBody() {
        bitField0_ = (bitField0_ & ~0x00000001);
        body_ = getDefaultInstance().getBody();
        onChanged();
        return this;
      }
      /**
       * <code>optional string body = 1;</code>
       */
      public Builder setBodyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        body_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString tempBody_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes temp_body = 2;</code>
       */
      public boolean hasTempBody() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional bytes temp_body = 2;</code>
       */
      public com.google.protobuf.ByteString getTempBody() {
        return tempBody_;
      }
      /**
       * <code>optional bytes temp_body = 2;</code>
       */
      public Builder setTempBody(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        tempBody_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes temp_body = 2;</code>
       */
      public Builder clearTempBody() {
        bitField0_ = (bitField0_ & ~0x00000002);
        tempBody_ = getDefaultInstance().getTempBody();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.mars.masterserver.net.decoder.Content)
    }

    static {
      defaultInstance = new Content(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.mars.masterserver.net.decoder.Content)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mars_masterserver_net_decoder_MsgRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mars_masterserver_net_decoder_MsgRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mars_masterserver_net_decoder_MsgResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mars_masterserver_net_decoder_MsgResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_mars_masterserver_net_decoder_Content_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_mars_masterserver_net_decoder_Content_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n3com/mars/masterserver/net/decoder/MsgP" +
      "rotocol.proto\022!com.mars.masterserver.net" +
      ".decoder\"U\n\nMsgRequest\022\n\n\002id\030\001 \001(\t\022;\n\007co" +
      "ntent\030\002 \001(\0132*.com.mars.masterserver.net." +
      "decoder.Content\"V\n\013MsgResponse\022\n\n\002id\030\001 \001" +
      "(\t\022;\n\007content\030\002 \001(\0132*.com.mars.masterser" +
      "ver.net.decoder.Content\"*\n\007Content\022\014\n\004bo" +
      "dy\030\001 \001(\t\022\021\n\ttemp_body\030\002 \001(\014"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_mars_masterserver_net_decoder_MsgRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_mars_masterserver_net_decoder_MsgRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_mars_masterserver_net_decoder_MsgRequest_descriptor,
        new java.lang.String[] { "Id", "Content", });
    internal_static_com_mars_masterserver_net_decoder_MsgResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_mars_masterserver_net_decoder_MsgResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_mars_masterserver_net_decoder_MsgResponse_descriptor,
        new java.lang.String[] { "Id", "Content", });
    internal_static_com_mars_masterserver_net_decoder_Content_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_com_mars_masterserver_net_decoder_Content_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_mars_masterserver_net_decoder_Content_descriptor,
        new java.lang.String[] { "Body", "TempBody", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
